#%RAML 1.0
title: Retail Orders System API
version: v2.0
baseUri: http://localhost:8081/api

uses:
  order:  /exchange_modules/org.mule.templates/retail-order-types/1.0.2/retail_order_types.raml


types:   
  StatusRequest:
    properties:
      status: order.Status

  OrderResponse:
    type: order.OrderSummary

  OrderCollectionResponse:
    type: order.OrderSummary[]

  MessageResponse: 
    properties: 
      message: string
      identifier?: string  

/orders:
  /customer/{customerId}:
    get:
      displayName: Get orders for customer
      description: Lists the customer orders
      queryParameters:
        trackingNumber:
          displayName: Order tracking number
          required: false
          type: string
        username:
          displayName: Username
          required: true
          type: any
        password:
          displayName: Password
          required: true
          type: any
      responses:
        200:
          body:
            application/json:
              type: OrderCollectionResponse
              example: !include examples/order_collection_get_response.yaml
    post:
      displayName: Create order
      description: Create a new order
      queryParameters:
        username:
          displayName: Username
          required: true
          type: any
        password:
          displayName: Password
          required: true
          type: any
      body:
        application/json:
          type: OrderResponse
          example: !include examples/order_post_request.yaml
      responses:
        201:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order was created",
                  "identifier": "51c0bde6-7e64-11e7-bb31-be2e44b06b34"
                }
        400:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order not created"
                }
        404:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Customer not found"
                }        
  /{orderId}:
    get:
      displayName: Get order
      queryParameters:
        username:
          displayName: Username
          required: true
          type: any
        password:
          displayName: Password
          required: true
          type: any
      responses:
        200:
          body:
            application/json:
              type: OrderResponse              
              example: !include examples/order_get_response.yaml

        404:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order not found"
                }
    put:
      displayName: Update order
      queryParameters:
        username:
          displayName: Username
          required: true
          type: any
        password:
          displayName: Password
          required: true
          type: any
      body:
        application/json:
          type: OrderResponse
          example:  !include examples/order_put_request.yaml
      responses:
        200:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order was updated"
                }
        400:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order not updated"
                }
        404:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order not found"
                }                    
    delete:
      displayName: Delete order
      queryParameters:
        username:
          displayName: Username
          required: true
          type: any
        password:
          displayName: Password
          required: true
          type: any
      responses:
        200:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order was deleted"
                }
        400:
          body:
            application/json:
              type: MessageResponse
              example: |
                {
                  "message": "Order not deleted"
                }
